### ISSUE TITLE
Bug with null serialization/deserialization

### ISSUE THREAD

**Issue by spaceorc** [skbkontur/GroBuf#3] opened 2017-06-27 09:00 UTC
I have a variable of reference type with value of **null**.
I serialize it and get `byte[] {0}`, then deserialize and get **not null** value.
Example:

```C#
class Serialization_Test
{
    class MyClass
    {
        public int Value { get; set; }
    }

    [Test]
    public void Test()
    {
        var serializer = new Serializer(new PropertiesExtractor());
        var bytes = serializer.Serialize<MyClass>(null);
        var myClass = serializer.Deserialize<MyClass>(bytes);
        Assert.IsNull(myClass);
    }
}
```

fails with 
```
Expected: null
  But was:  <Serialization_Test+MyClass>
```

**Comment by homuroll** [comment] 2017-06-27 10:21
Yeah, that is a well-known issue. Long time ago we explicitly defined this behaviour as a correct one, but I think that if the option `WriteEmptyObjects` is on, than Grobuf needs to deserialize as is.

**Comment by AndrewKostousov** [comment] 2017-10-20 21:39
Closing this issue since the described behavior is by design.

**Closed by AndrewKostousov** 2017-10-20 21:39 UTC
Labels: wontfix
